version: '3.7'
services:
  mongodb:
    image: mongo:6.0
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    command: ["--replSet", "dbrs", "--bind_ip_all"]
    volumes:
      - db:/data/db
      - .docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  db:
