FROM node:18-alpine AS builder

WORKDIR /build

COPY . /build
RUN npm ci && npm run build && npm prune --omit=dev

FROM node:18-alpine

WORKDIR /app
COPY --from=builder /build/dist /app/dist
COPY --from=builder /build/node_modules /app/dist/node_modules


EXPOSE 3000

ENTRYPOINT ["node", "dist/main.js"]
